@startuml
skinparam backgroundColor transparent
autonumber

box sequence diagram arm_node

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml